# config file for alacritty
import = [
    "~/.config/alacritty/themes/themes/catppuccin-macchiato.toml"
]

[env]
    TERM = "xterm-256color"
    WININT_X11_SCALE_FACTOR = "1.0"

[shell]
    program = "zsh"
    args = ["--login", "-c", "tmux attach || tmux"]


[window]
    padding.x = 10
    padding.y = 10
    decorations = "Buttonless"
    opacity = 1.0
    blur = true
    dynamic_title = true
    resize_increments = true
    option_as_alt = "Both"
    startup_mode = "Windowed"
    dimensions = { columns = 80, lines = 120 }

[scrolling]
    history = 10000
    multiplier = 3


[font]
    normal.family = "FiraCode Nerd Font Mono"
    size = 14

[colors]
    # primary = { background = "0x000000", dim_foreground = "#AAAAAA"}

[keyboard]
    bindings = [
        { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
        { key = "L", mods = "Control|Shift", chars = "l" },
    ]

[bell]
    # command = { program = "osascript", args = ["-e", "beep"] }
    command = "None"

    
